const TEST_API_LOADING = 'TEST_API_LOADING';
const TEST_API_SUCCESS = 'TEST_API_SUCCESS';
const TEST_API_FAILURE = 'TEST_API_FAILURE';

export const testApiActions = {
  TEST_API_LOADING,
  TEST_API_SUCCESS,
  TEST_API_FAILURE,
};
